# 設定駆動型書類生成システム設定ファイル
# このファイルから契約書類を自動生成します

# ====================
# 組織基本情報
# ====================
organization:
  name: "マルスカフェ"
  full_name: "マルスカフェ バーチャルオフィス"
  postal_code: "807-0085"
  address: "福岡県北九州市八幡西区塔野１丁目１４‐２２"
  tel: "070-8381-1066"
  email: "marusucafe@gmail.com"
  website: "https://www.instagram.com/marusu_cafe/"

# ====================
# 法務情報
# ====================
legal:
  jurisdiction: 福岡地方裁判所 # 管轄裁判所
  applicable_law: 日本法 # 準拠法
  aml_compliance: true # 犯罪収益移転防止法対応
  privacy_policy_required: true # 個人情報保護方針の同意必須

# ====================
# サービス料金（月額）
# ====================
services:
  virtual_office:
    name: バーチャルオフィスサービス
    price: 2200
    unit: month
    required: true # 必須サービス
    description: 法人登記・住所利用サービス

  mail_receipt:
    name: 郵便受け取りサービス
    price: 1100
    unit: month
    required: false
    description: 郵便物の受取・保管サービス

  mail_forward:
    name: 郵便転送サービス
    price: 3300
    unit: month
    required: false
    description: 指定住所への郵便物転送サービス

# ====================
# 契約条件
# ====================
terms:
  membership:
    min_age: 18 # 最低年齢
    admin_fee_refundable: false # 事務手数料返金不可
    id_verification_required: true # 身分証明書必須

  cancellation:
    notice_period_months: 3 # 退会予告期間（月）
    immediate_cancellation_fee_months: 3 # 即時退会時の料金（月分）

  mail_retention:
    default_days: 14 # 通常保管期間（日）
    corporate_days: 30 # 法人向け保管期間（日）

# ====================
# 支払い方法
# ====================
payment_methods:
- id: bank_transfer
  name: 銀行振り込み
  name_en: Bank Transfer

- id: direct_debit
  name: 口座振替
  name_en: Account Transfer

# ====================
# 郵便物取扱いルール
# ====================
mail_rules:
  # 受取不可郵便物
  prohibited_items:
  - 現金書留
  - 内容証明
  - 特別送達
  - 本人限定受取郵便
  - 着払いのもの
  - 代金引換
  - 料金不足のもの（事前相談が無い場合）
  - 生き物
  - 危険物
  # 特殊郵便物の取扱い
  special_handling:
    simple_registered: 代筆・捺印での受取可 # 簡易書留
    specific_record: 代筆・捺印での受取可 # 特定記録
    letter_pack_plus: 代筆・捺印での受取可 # レターパックプラス

  # 責任制限
  liability:
    loss_theft: 免責 # 紛失・盗難
    delivery_delay: 免責 # 配送遅延
    damage: 免責 # 破損

# ====================
# 入会資格条件
# ====================
eligibility:
- 満18歳以上の個人、または法人であること
- 本規約の内容を承諾し、遵守すること
- 有効な身分証明書を提示できること
- 過去に当社運営施設で除名処分を受けていないこと（ただし当社が再入会を認めた場合を除く）
- その他、当社が入会を相応しいと判断した者

# ====================
# 禁止事項
# ====================
prohibited_actions:
- 当社または他の会員の名誉、信用を著しく傷つける行為
- 当社の許可なく、当社の住所を利用して営業行為や勧誘を行うこと
- 法令または公序良俗に反する事業を行うこと
- 当社の業務を妨げる行為
- その他、当社が会員として不適切と判断する行為

# ====================
# 書類メタデータ
# ====================
document_info:
  version: "1.0.0"
  established_date: "2025年1月27日"
  last_updated: "2025年1月27日"

# ====================
# 書類生成設定
# ====================
documents:
- id: application_form
  title: バーチャルオフィス利用申込書
  template: templates/application_form.md.j2
  output: current/バーチャルオフィス申込書.md

- id: terms_of_service
  title: バーチャルオフィス会員規約
  template: templates/terms_of_service.md.j2
  output: current/会員規約.md

- id: postal_contract_corporate
  title: 郵便サービス契約書（法人）
  template: templates/postal_contract_corporate.md.j2
  output: current/郵便サービス契約書_法人.md
